### ISSUE TITLE
Escape should exit help dialogue

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#53] opened 2017-02-13 21:39 UTC
Seems I need to delete the help message with backspace

**Comment by MasseGuillaume** [comment] 2017-02-15 10:05
Esc should delete the help message by default.

**Comment by MasseGuillaume** [comment] 2017-02-15 17:37
Hum, cannot reproduce :S

**Comment by olafurpg** [comment] 2017-02-20 14:02
I am able to reproduce the error in firefox and chrome but not safari. I suspect this has to do with me using vim-emulator browser extensions in chrome+firefox but no safari, but I find that a weird reason because I'm able to use the other hotkeys such as cmd+enter.

**Comment by MasseGuillaume** [comment] 2017-02-20 14:06
Ok, I think I will close this since it looks it's based on your personal setup. You have the clear button if need be.

**Comment by olafurpg** [comment] 2017-02-20 14:07
Yup was thinking the same.

**Closed** 2017-02-20 14:07 UTC
